language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: CHECK_PHP_SYNTAX="yes"
    - php: 7.2

before_install:
  # remove xdebug to speed up everything
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - vendor/bin/phpunit
  - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then vendor/bin/php-cs-fixer fix src --dry-run --diff; fi;
