language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: CHECK_PHP_SYNTAX="yes"
    - php: 7.2

install:
  - composer install

script:
  - vendor/bin/phpunit
  - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then composer check-cs; fi;
