#!/usr/bin/env php
<?php

/*
 * This file is part of the easybook application.
 *
 * (c) Javier Eguiluz <javier.eguiluz@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require_once __DIR__.'/app/autoload.php';

use Easybook\DependencyInjection\Application;
use Easybook\Console\ConsoleApplication;

$app = new Application();
$console = new ConsoleApplication($app);
$console->run();