#!/usr/bin/env php
<?php

/*
 * This file is part of the easybook application.
 *
 * (c) Javier Eguiluz <javier.eguiluz@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (is_dir($dir = __DIR__.'/vendor')) {
    require $dir . '/autoload.php'; 
} elseif (is_dir($dir = __DIR__ . '/../../../vendor')) {
    require $dir . '/autoload.php';
} else {
    echo 'You must set up the project dependencies, run the following command: "php composer.phar install"';
    die(1);
}

use Easybook\DependencyInjection\Application;
use Easybook\Console\ConsoleApplication;

$app = new Application();
$console = new ConsoleApplication($app);
$console->run();
