# default values for the main book configuration options
parameters:
    book_title: 'Writing CLI Apps'
    book_author: 'Tomas Votruba'
    book_edition: ~
    book_language: 'en'
    book_publication_date: ~
    book_contents: ~
