# default values for the main book configuration options
parameters:
    book_title: "Untitled"
    book_author: "Anonymous"
    book_edition: ~
    book_language: en
    book_publication_date: ~
    book_contents: ~
    book_editions: ~
