# default values for the configuration options of edition format
parameters:
    book_editions:
        -
            format: ~
            images_base_dir: 'images/'
            include_styles: true
            isbn: ~
            labels: ['appendix', 'chapter', 'figure']
            # margins
            margin_top: '25mm'
            margin_bottom: '25mm'
            margin_inner: '30mm'
            margin_outter: '20mm'

            page_size: 'A4'
            theme: 'clean'

            toc_deep: 2
            tco_elements: ['appendix', 'chapter']

            two_sided: true
