services:
    _defaults:
        public: true
        autowire: true

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\Finder\Finder: ~
    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Console\Application:
        arguments:
            $name: 'easybook'
            $version: '%version%'

    Easybook\:
        resource: '../../../src/Easybook'

    # from providers
    GeSHi:
        class: 'GeSHi'
        calls:
            - ['enable_classes'] # this must be the first method (see Geshi doc)
            - ['enable_classes', ['%app.charset%']]
            - ['enable_line_numbers', ['!php/const GESHI_NO_LINE_NUMBERS']]
            - ['enable_keyword_links', [false]]

    EasySlugger\Utf8Slugger:
        arguments:
            - '%slugger_separator%'


    Twig_Environment:
        class: 'Twig_Environment'
        arguments:
            $options: '%twig.options%'

        calls:
            # @todo use collector
             - ['addExtension', ['@Easybook\Util\TwigCssExtension']]

#        if (null !== $bookConfig = $app['publishing.book.config']) {
#        $twig->addGlobal('book', $bookConfig['book']);
#        $publishingEdition = $app['publishing.edition'];
#        $editions = $app->book('editions');
#        $twig->addGlobal('edition', $editions[$publishingEdition]);

    Michelf\MarkdownExtra: ~
