services:
    _defaults:
        public: true
        autowire: true

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\Finder\Finder: ~
    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Console\Application:
        arguments:
            $name: 'easybook'
            $version: '%version%'

    Easybook\:
        resource: '../src/Easybook'
