services:
    _defaults:
        public: true
        autowire: true

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\Finder\Finder: ~
    Symfony\Component\Filesystem\Filesystem: ~

    Easybook\:
        resource: '../src/Easybook'
