imports:
    - { resource: 'parameters/*.yml' }
    - { resource: '../../app/Resources/Translations/labels.en.yml' }

parameters:
    # to be configured by the user
    book_slug: ''
    book_temporary_cache_dir: '%kernel.project_dir%/_temp_books'

    cover_image: ~

    # global directories location
    resources_dir: '%kernel.project_dir%/app/Resources'
    translations_dir: '%kernel.project_dir%/app/Resources/Translations'
    app.dir.skeletons: '%kernel.project_dir%/app/Resources/Skeletons'
    skeleton_book_directory: '%kernel.project_dir%/app/Resources/Skeletons/Book'
    themes_dir: '%kernel.project_dir%/app/Resources/Themes'

    # publishing process variables
    # holds the app theme dir for the current edition
    book_dir: '...'

    publishing.dir.app_theme: ''

    book_source_dir: '%kernel.project_dir%/book' # default value that can be overriden by "--dir" cli option
    book_contents_dir: '%book_dir%/Contents'
    book_resources_dir: '%book_dir%/Resources'
    book_templates_dir: '%book_resources_dir/Templates'

    # kindlegen bin path - required fro MOBI
    kindlegen_path: ~

    # wkhtmlpdf bin path - required fro PDF
    wkhtmlpdf_path: ~
