imports:
    - { resource: 'parameters/*.yml' }

parameters:
    # to be configured by the user
    book_slug: ''

    # global directories location
    app.dir.doc: '%kernel.project_dir%/doc'
    app.dir.resources: '%kernel.project_dir%/app/Resources'
    app.dir.plugins: '%kernel.project_dir%/src/Easybook/Plugins'
    app.dir.translations: '%kernel.project_dir%/app/Resources/Translations'
    app.dir.skeletons: '%kernel.project_dir%/app/Resources/Skeletons'
    skeleton_book_directory: '%kernel.project_dir%/app/Resources/Skeletons/Book'
    app.dir.themes: '%kernel.project_dir%/app/Resources/Themes'

    # publishing process variables
    # holds the app theme dir for the current edition
    book_dir: '...'

    publishing.dir.app_theme: ''
    publishing.dir.book: ''
    publishing.dir.contents: ''
    publishing.dir.resources: ''
    publishing.dir.plugins: ''
    publishing.dir.templates: ''
    publishing_dir_output: '%kernel.project_dir%/output'
    publishing.dir.slug: '%kernel.project_dir%/output'
    publishing.items: []

    # the specific item currently being parsed/modified/decorated/...
    publishing.active_item: []
    publishing.active_item.toc: []

    publishing.book.items: []

    # the real TOC used to generate the book (needed for html_chunked editions)
    publishing.book.toc: []

    # holds all the internal links (used in html_chunked and epub editions)
    publishing.links: []
    publishing.list.images: []
    publishing.list.tables: []

    # kindle gen
    kindlegen.path: ~

    # the common installation dirs for KindleGen in several OS
    kindlegen.default_paths:
        # Mac OS X & Linux
        - '/usr/local/bin/kindlegen'
        - '/usr/bin/kindlegen'
        # Windows
        - 'c:\KindleGen\kindlegen'

    # -c0: no compression
    # -c1: standard DOC compression
    # -c2: Kindle huffdic compression
    # -verbose: (even more) verbose output
    # -western: force Windows-1252 charset
    # -gif: transform book images to GIF
    kindlegen.command_options: '-c1'
