services:
    _defaults:
        public: true
        autowire: true

    Twig_Loader_Chain:
        class: 'Twig_Loader_Chain'
        factory: ['@Easybook\Twig\TwigLoaderFactory', 'create']

    Twig\Environment:
        arguments:
            $options:
                cache: '%kernel.cache_dir%/twig'
                autoescape: false
