imports:
    - { resource: 'services/*.yml' }

services:
    _defaults:
        public: true
        autowire: true

    Easybook\Console\Application: ~

    Symfony\Component\Console\Application:
        alias: 'Easybook\Console\Application'

    Easybook\:
        resource: '..'
        exclude: '../{Events,Book/*.php}'

    # from providers
    GeSHi:
        class: 'GeSHi'
        calls:
            - ['enable_classes'] # this must be the first method (see Geshi doc)
            - ['enable_classes', ['UTF-8']]
            - ['enable_line_numbers', ['!php/const GESHI_NO_LINE_NUMBERS']]
            - ['enable_keyword_links', [false]]

    Michelf\MarkdownExtra: ~

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

