services:
    _defaults:
        public: true
        autowire: true

    Symfony\Component\EventDispatcher\EventDispatcher: ~

    Symfony\Component\Finder\Finder: ~
    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Console\Helper\QuestionHelper:

    Easybook\Console\Application: ~

    Symfony\Component\Console\Application:
        alias: 'Easybook\Console\Application'

    Easybook\:
        resource: '..'

    # from providers
    GeSHi:
        class: 'GeSHi'
        calls:
            - ['enable_classes'] # this must be the first method (see Geshi doc)
            - ['enable_classes', ['%app.charset%']]
            - ['enable_line_numbers', ['!php/const GESHI_NO_LINE_NUMBERS']]
            - ['enable_keyword_links', [false]]

    EasySlugger\Utf8Slugger:
        arguments:
            $separator: '%slugger_separator%'

    Twig\Environment:
        arguments:
            $options:
                autoescape: false
                cache: '%kernel.cache_dir%/Twig'
                charset: '%app.charset%'
                debug: '%kernel.debug%'
                strict_variables: '%kernel.debug%'

    Twig_Loader_Filesystem:
        class: 'Twig_Loader_Filesystem'
        factory: ['@Easybook\Twig\TwigLoaderFactory', 'create']
#        if (null !== $bookConfig = $app['publishing.book.config']) {
#        $twig->addGlobal('book', $bookConfig['book']);
#        $publishingEdition = $app['publishing.edition'];
#        $editions = $app->book('editions');
#        $twig->addGlobal('edition', $editions[$publishingEdition]);

    Michelf\Markdown: ~
    Michelf\MarkdownExtra: ~

    # Console
    Symfony\Component\Console\Style\SymfonyStyle:
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: Symfony\Component\Console\Input\ArgvInput
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
