parameters:
    book:
        title: "Change this: Book name"
        author: "Change this: Author Name"
        subtitle: "First edition"
        publication_date: ~

        contents:
            # available content types: acknowledgement, afterword, appendix, author,
            # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
            # glossary, introduction, license, lof (list of figures), lot (list of
            # tables), part, preface, prologue, title, toc (table of contents)
            - { element: cover }
            - { element: toc   }
            - { element: chapter, number: 1, content: chapter1.md }
            - { element: chapter, number: 2, content: chapter2.md }

        editions:
            ebook:
                format:         epub
                include_styles: true
                labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
                theme:          clean
                toc:
                    deep:       1
                    elements:   ["appendix", "chapter", "part"]

            kindle:
                format:         mobi
                include_styles: true
                labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
                theme:          clean
                toc:
                    deep:       1
                    elements:   ["appendix", "chapter", "part"]

            print:
                format:         pdf
                include_styles: true
                labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
                margin:
                    top:        25mm
                    bottom:     25mm
                    inner:      30mm
                    outer:      20mm
                page_size:      A4
                theme:          clean
                toc:
                    deep:       2
                    elements:   ["appendix", "chapter", "part"]
                two_sided:      true
